### ISSUE TITLE
RE2.QuoteMeta doesn’t work with strings containing null byte.

### ISSUE THREAD

**Issue by manueljacob** [mudge/re2#130]
I’d expect `RE2.QuoteMeta("abc\0def")` to return `"abc\\x00def"` but it returns `"abc"`. The reason is that in https://github.com/mudge/re2/blob/v2.6.0/ext/re2/re2.cc#L1756, `RSTRING_PTR` is used to convert the Ruby String to `char *`. `RE2::QuoteMeta` then interprets it as a null-terminated string. In addition to the truncation problem, according to the [Ruby documentation](https://docs.ruby-lang.org/en/3.2/extension_rdoc.html#label-Data+Type+Conversion), the result of `RSTRING_PTR` may not be NUL-terminated, potentially leading to a buffer over-read.

**Comment by mudge** [comment]
Thanks for reporting this, @manueljacob.

This should now be fixed in the newly released [2.7.0](https://github.com/mudge/re2/releases/tag/v2.7.0), can you please let me know if that resolves your issue?

It should also fix handling of null bytes across the library where possible (note that null bytes are _not_ valid in capturing group names as that is dictated by RE2 itself).

**Comment by manueljacob** [comment]
It works for me, thank you!
