### ISSUE TITLE
Different behavior for '^'

### ISSUE THREAD

**Issue by sk-** [mudge/re2#29]
In plain ruby we have:

```ruby
Regexp.new('^a').match("\na")
 => #<MatchData "a">
```

whereas in `re2`:

```ruby
RE2::Regexp.new('^a').match("\na")
 => false
```

**Comment by mudge** [comment]
This is due to a difference in the underlying [Google re2 library's syntax](https://github.com/google/re2/wiki/Syntax) which isn't 100% compatible with PCRE: in order for `^` to match the beginning of a line, you need to use the multi-line mode flag.

```ruby
RE2::Regexp.new('(?m)^a').match("\na")
=> true
```

Or, using a capturing group to return the match:

```ruby
RE2::Regexp.new('(?m)(^a)').match("\na")
=> #<RE2::MatchData "a" 1:"a">
```

**Comment by sk-** [comment]
Could you add a section to the Readme stating the differences and incompatibilities of `re2` compared to ruby's `Regexp`.
